env:
  browser: true
  commonjs: true
  es2021: true
extends: prettier
ignorePatterns:
  - .prettierrc
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always